- name: Signature Romantique Reverie Headdress
  image: DSC_3166.jpg
  link: hair_accessories/signature_reverie_romantique_headdress.html
  description: Headdress with intricate signature lace
- name: The Edith Rose Key Necklace
  image: DSCF3214.jpg
  link: jewelry/the_edith_rose_key_necklace.html
  description: Rose cabochon Key Pendant Necklace
- name: The Edith Rose Filigree Bracelet
  image: DSCF3319.jpg
  link:  jewelry/the_edith_rose_filigree_bracelet.html
  description: Rose Cabochon Filigree Bracelet
- name: The Edith Rose Ring
  image: DSCF3309.jpg
  link:  jewelry/the_edith_rose_ring.html
  description: Rose Cabochon Ring
- name: The Edith Cameo Key Necklace
  image: DSCF3294.jpg
  link: jewelry/the_edith_cameo_key_necklace.html
  description: Vintage Cameo Key Pendant Necklace
- name: The Edith Rose Filigree Earrings
  image: DSCF3314.jpg
  link: jewelry/the_edith_rose_filigree_earrings.html
  description: Rose Cabochon Filigree Earrings
- name: The Edith Vintage Cameo Princess Necklace
  image: DSCF3210.jpg
  link: jewelry/the_edith_vintage_cameo_princess_necklace.html
  description: Vintage Cameo Princess Necklace
- name: Michelle Rose Bouquet
  image: IMG_2048.jpg
  link: other_accessories/michelle_rose_bouquet.html
  description: Rose Corsage Bouquet
- name: Michelle Rose Headdress
  image: IMG_2077.jpg
  link: hair_accessories/michelle_rose_headdress.html
  description: Headdress with rose lace plus optional flowers add on
- name: Aria Headdress
  image: PXL_20240611_220055579.RAW-01.COVER.jpg
  link: hair_accessories/aria_headdress.html
  description: Headdress with gathered fabric, braid, and ribbon
- name: Aria Double Ruffle Lace Cuffs
  image: PXL_20240611_220600223.RAW-01.COVER.jpg
  link: other_accessories/aria_double_ruffle_lace_cuffs.html
  description: Lace cuffs with two layers of tulle lace ruffles
- name: Aria Lace-up Armwarmers
  image: PXL_20240612_004804216.RAW-01.COVER.jpg
  link: other_accessories/aria_lace_up_armwarmers.html
  description: Armwarmers with a lace-up design